github: [devinschumacher]

open_collective: devinschumacher

custom: [
  "https://store.serp.co/template-downloader/",
  "https://serp.co/products/template-downloader/reviews/",
  "https://serpapps.github.io/template-downloader",
  "https://devinschumacher.com/template-downloader",
]