github: [devinschumacher]
open_collective: devinschumacher
custom: [
  "https://serpapps.github.io/template-downloader",
  "https://serp.co/products/template-downloader/reviews/",
  "https://devinschumacher.com/template-downloader"
]
